name: Airflow CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "airflow/**"
      - ".github/workflows/airflow-ci.yml"

  push:
    branches:
      - main
    paths:
      - "airflow/**"
      - ".github/workflows/airflow-ci.yml""

permissions:
  contents: read

jobs:
  airflow-ci:
    name: Airflow CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check Python syntax
        run: |
          python -m compileall airflow/dags

      - name: Build Airflow CI image
        run: |
          docker build \
            --build-arg AIRFLOW_VERSION=3.3.0 \
            -t airflow-ci:"$GITHUB_SHA" \
            airflow

      - name: Check DAG import errors
        run: |
          docker run \
            --rm \
            airflow-ci:"$GITHUB_SHA" \
            airflow dags list-import-errors \
              --output=json \
            > import-errors.json

          cat import-errors.json

      - name: Fail if DAG import errors exist
        run: |
          python - <<'PY'
          import json
          import sys

          with open("import-errors.json", encoding="utf-8") as file:
              errors = json.load(file)

          if errors:
              print("DAG import errors detected:")
              print(json.dumps(errors, indent=2))
              sys.exit(1)

          print("No DAG import errors.")
          PY
